apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sbom-test 
  janus-idp.io/tekton: sbom-test
  backstage.io/kubernetes-id: sbom-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sbom-test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  