apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sbom-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbom-test 
  name: sbom-test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: sbom-test 
